name: Deploy to Aliyun OSS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: build
              run: npm run docs:build
            
            - name: Deploy to SFTP
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  username: ${{ secrets.SFTP_USERNAME }}
                  ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
                  server: ${{ secrets.SFTP_SERVER }}
                  remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
                  local_path: ./docs/.vitepress/dist