name: Deploy Website
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 


            - name: Install dependencies
              run: npm install -D

            - name: Build website
              run: npm run docs:build